"""Image entity for Seismic World Earthquakes — displays the USGS ShakeMap."""
from __future__ import annotations

import asyncio
import logging
from datetime import datetime

import aiohttp

from homeassistant.components.image import ImageEntity
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity
from homeassistant.util import dt as dt_util

from .const import DOMAIN, SHAKEMAP_MIN_MAGNITUDE
from .coordinator import SeismicWorldEarthquakesCoordinator

_LOGGER = logging.getLogger(__name__)

_SHAKEMAP_FETCH_TIMEOUT = 15


async def async_setup_entry(
    hass: HomeAssistant,
    entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up image entities."""
    coordinator: SeismicWorldEarthquakesCoordinator = entry.runtime_data
    async_add_entities([SeismicShakemapImage(hass, coordinator)])


class SeismicShakemapImage(CoordinatorEntity[SeismicWorldEarthquakesCoordinator], ImageEntity):
    """
    Displays the USGS ShakeMap intensity image for the strongest earthquake.

    ShakeMaps are only generated by USGS for events with magnitude ≥ 4.5.
    When no event reaches this threshold, the image will be unavailable.
    """

    _attr_has_entity_name = True
    _attr_translation_key = "shakemap"
    _attr_icon = "mdi:map-legend"
    _attr_content_type = "image/jpeg"

    def __init__(
        self,
        hass: HomeAssistant,
        coordinator: SeismicWorldEarthquakesCoordinator,
    ) -> None:
        """Initialise."""
        CoordinatorEntity.__init__(self, coordinator)
        ImageEntity.__init__(self, hass)
        self._attr_unique_id = f"{coordinator.config_entry.entry_id}_shakemap"
        self._current_url: str | None = None
        self._attr_image_last_updated: datetime | None = None

    @property
    def device_info(self) -> DeviceInfo:
        return DeviceInfo(
            identifiers={(DOMAIN, self.coordinator.config_entry.entry_id)},
            name=self.coordinator.config_entry.title,
            manufacturer="U.S. Geological Survey (USGS)",
            model="Earthquake Hazards Program API",
            entry_type=DeviceEntryType.SERVICE,
            configuration_url="https://earthquake.usgs.gov/earthquakes/feed/",
        )

    def _handle_coordinator_update(self) -> None:
        """Update the image timestamp when the shakemap URL changes."""
        if self.coordinator.data is None:
            return
        new_url = self.coordinator.data.shakemap_url
        if new_url != self._current_url:
            self._current_url = new_url
            self._attr_image_last_updated = dt_util.now() if new_url else None
        self.async_write_ha_state()

    async def async_image(self) -> bytes | None:
        """
        Fetch and return the ShakeMap image bytes.

        Returns None if no ShakeMap is available (magnitude < 4.5 or no data).
        """
        if not self._current_url:
            return None

        session = async_get_clientsession(self.hass)
        try:
            async with asyncio.timeout(_SHAKEMAP_FETCH_TIMEOUT):
                async with session.get(self._current_url) as resp:
                    if resp.status == 200:
                        return await resp.read()
                    _LOGGER.debug(
                        "ShakeMap image returned status %d for URL: %s",
                        resp.status,
                        self._current_url,
                    )
        except asyncio.TimeoutError:
            _LOGGER.debug("Timeout fetching ShakeMap image from %s", self._current_url)
        except aiohttp.ClientError as err:
            _LOGGER.debug("Error fetching ShakeMap image: %s", err)
        return None

    @property
    def extra_state_attributes(self) -> dict:
        attrs = {
            "shakemap_available": self._current_url is not None,
            "min_magnitude_for_shakemap": SHAKEMAP_MIN_MAGNITUDE,
        }
        if self.coordinator.data and self.coordinator.data.strongest:
            eq = self.coordinator.data.strongest
            attrs["earthquake_id"] = eq.earthquake_id
            attrs["magnitude"] = eq.magnitude
            attrs["place"] = eq.place
        if self._current_url:
            attrs["shakemap_url"] = self._current_url
        return attrs
